remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Snow on the Beach
description: An exploration of outliers in Taylor Swift's albums
show_downloads: true